# Generated by Django 4.1.1 on 2022-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='title_bg',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Bulgarian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_cs',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Czech)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_da',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Danish)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_de',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (German)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_el',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Greek)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(db_tablespace='', default=1, max_length=200, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_et',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Estonian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_fi',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Finnish)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (French)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ga',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Irish)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_hr',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Croatian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_hu',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Hungarian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_it',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Italian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_lt',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_lv',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Latvian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_mt',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Maltese)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_nl',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Dutch)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_pl',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Polish)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Portuguese)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ro',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Romanian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_sk',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Slovak)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_sl',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Slovene)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_sv',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Swedish)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Uzbekistan)'),
        ),
        migrations.DeleteModel(
            name='CategoryTranslations',
        ),
    ]
