# Generated by Django 4.1.2 on 2022-11-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='rating',
        ),
    ]
