# Generated by Django 4.1.1 on 2022-10-05 11:46

from django.db import migrations, models
import project.apps.ideas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='picture',
            field=models.ImageField(default=1, upload_to=project.apps.ideas.models.upload_to, verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
