# Generated by Django 4.1.2 on 2022-11-02 10:01

from django.db import migrations, models
import project.apps.accounts.models_02


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=project.apps.accounts.models_02.upload_to, verbose_name='Avatar'),
        ),
    ]
