# Generated by Django 4.1.2 on 2022-10-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ('order',), 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='productphoto',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=3, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
